#! /bin/python3.9

"""
FIXME
1 . fix the folder arguments 

"""

import os
import argparse
import zipfile
import rarfile
from glob import glob
from shutil import rmtree

from pdf2image import convert_from_path

import re

parser = argparse.ArgumentParser()
parser.add_argument("folder", help="Folder are the .cbz's files where...")
parser.add_argument("result", help="Name of the merged file...")
#parser.add_argument("cover", help="Please, I need the file cover...")
args = parser.parse_args()

pdfFiles = glob(f'{args.folder}/*.pdf',recursive=True)
pdfFiles.sort(key=lambda var:[int(x) if x.isdigit() else x for x in re.findall(r'[^0-9]|[0-9]+', var)])

saveFolder = "tempZ" 
os.mkdir(saveFolder)

# Store Pdf with convert_from_path function
pages = 0
for index, file in enumerate(pdfFiles):
    print(f'{index}/{len(pdfFiles)}', end=' ')
    images = convert_from_path(file)
    print(f' --> {len(images)}', end=' ')
    for i in range(len(images)):
        images[i].save(f"{saveFolder}/f{index} - p{i}.jpg", 'JPEG')
    print('OK')

content = glob(f"{saveFolder}/*")

content.sort(key=lambda var:[int(x) if x.isdigit() else x for x in re.findall(r'[^0-9]|[0-9]+', var)])

#recompress files 
with zipfile.ZipFile(args.result,"w") as zf:
    for page in content:
        page = page 
        zf.write(page)
    #zf.write(coverName)

#delete the temp folder
rmtree(saveFolder)

