#! /bin/python3.9

"""
FIXME
1 . fix the folder arguments 

"""

import os
import argparse
import zipfile
import rarfile
from glob import glob
from shutil import rmtree, copyfile

from pdf2image import convert_from_path

import re

parser = argparse.ArgumentParser()
parser.add_argument("folder", help="Folder are the .cbz's files where...")
parser.add_argument("cover", help="Please, I need to a path to file cover...")
parser.add_argument("result", help="Name of the merged file...")
args = parser.parse_args()

print("Looking for files...")
pdfFiles = glob(f'{args.folder}/*.pdf',recursive=True)
pdfFiles.sort(key=lambda var:[int(x) if x.isdigit() else x for x in re.findall(r'[^0-9]|[0-9]+', var)])

saveFolder = "tempZ" 
os.mkdir(saveFolder)

# Store Pdf with convert_from_path function
print("Extracting images...")
for index, file in enumerate(pdfFiles):
    print(f'{index}/{len(pdfFiles)-1}', end=' ')
    images = convert_from_path(file)
    print(f' --> {len(images)}', end=' ')
    for i in range(len(images)):
        images[i].save(f"{saveFolder}/f{index} - p{i}.jpg", 'JPEG')
    print('OK')

"""
import shutil

original = r'original path where the file is currently stored\file name.file extension'
target = r'target path where the file will be copied\file name.file extension'

shutil.copyfile(original, target)
"""
if '.png' in args.cover:
    coverType = '.png'
elif '.jpg' in args.cover:
    coverType = '.jpg'
else:
    printf("Failed do determinate the file type of the cover...")
    exit(1)

coverName = f'{saveFolder}/0000000-cover{coverType}'

content = glob(f"{saveFolder}/*")
content.sort(key=lambda var:[int(x) if x.isdigit() else x for x in re.findall(r'[^0-9]|[0-9]+', var)])

#recompress files 
print(f'Recompressing in a new file called {args.result}...')
with zipfile.ZipFile(args.result,"w") as zf:
    for page in content:
        page = page 
        zf.write(page)
    copyfile(args.cover,f'{coverName}')
    zf.write(coverName)
print(f'{args.result} saved.')
#delete the temp folder

rmtree(saveFolder)

